[workspace]
members = [
        "folgore-common",
        "folgore-nakamoto",
        "folgore-esplora",
        "folgore-plugin",
        "folgore-bitcoind",
]
resolver = "2"

[profile.release]
opt-level = 3
