[package]
name = "folgore-bitcoind"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
folgore-common = { path = "../folgore-common" }
bitcoincore-rpc = "0.17.0"
